# Use powerline
USE_POWERLINE="true"
# Has weird character width
# Example:
#    is not a diamond
HAS_WIDECHARS="false"
# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
#if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
#  source /usr/share/zsh/manjaro-zsh-prompt
#fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# make history nicer
# ------------------
HISTSIZE=1048576
HISTFILE="$HOME/.zsh_history"
SAVEHIST=$HISTSIZE
setopt appendhistory
setopt incappendhistory
setopt extendedhistory
setopt histignorealldups
setopt histignorespace

# zsh opts
# --------
setopt correct           # Auto-correct mistakes
setopt nocaseglob        # Case insensitive globbing
setopt numericglobsort   # Sort filesnames numerically when sane
setopt nobeep            # Don't beep
setopt autocd            # Automatically cd if only dirpath
setopt complete_aliases  # Allow for completion when using aliases

# Clone antidote (plugin manager) if necessary.
# ---------------------------------------------
[[ -e $HOME/.antidote ]] ||
git clone --depth=1 https://github.com/mattmc3/antidote.git $HOME/.antidote

# source antidote
source ${ZDOTDIR:-~}/.antidote/antidote.zsh

# initialize plugins statically with ${ZDOTDIR:-~}/.zsh_plugins.txt
antidote load

# ZSH VI MODE CONFIGURATION
function zvm_config() {
    ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
    ZVM_READKEY_ENGINE=$ZVM_READKEY_ENGINE_NEX
}

#source /usr/share/doc/fzf/examples/key-bindings.zsh
source /usr/share/fzf/key-bindings.zsh

alias v="nvim"
alias py="python3"
alias e="exit"
alias install="sudo pacman -S"
alias search="sudo pacman -Ss"
alias lg="lazygit"
alias pkgsearch="yay -Slq | fzf --multi --preview 'yay -Si {1}' | xargs -ro yay -S"

#export PATH="$PATH:/home/ppg/.local/share/bob/nvim-bin"
#export PATH="$PATH:/home/ppg/.cargo/bin"

#export EDITOR="/home/ppg/.local/share/bob/nvim-bin/nvim"
#export SUDOEDITOR="/home/ppg/.local/share/bob/nvim-bin/nvim"
#export SUDO_EDITOR="/home/ppg/.local/share/bob/nvim-bin/nvim"

export EDITOR="/usr/bin/nvim"
export SUDOEDITOR="/usr/bin/nvim"
export SUDO_EDITOR="/usr/bin/nvim"

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"
source /usr/share/nvm/nvm.sh
source /usr/share/nvm/bash_completion
source /usr/share/nvm/install-nvm-exec

#export NVM_DIR="$HOME/.config/nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
